name: python-testing

on: [push]
permissions:
  contents: write
  pull-requests: write
  issues: write
  checks: write

env:
  COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}

jobs:
  build:

    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: ["3.8"]

    steps:
      - name: Checkout pyrat-zero
        uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run linters
        run: pre-commit run --all-files --verbose
      - name: Run tests 🧪
        run: pytest --cov=algorithms --cov-report=term-missing --junit-xml=test-results.xml -vv tests
      - name: Run coverage
        run: |
          coverage html --directory=coverage_html_report
          coverage report --fail-under=0.97
      - name: Upload Coverage to Coveralls
        run: coveralls
      - name: Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

